### ISSUE TITLE
Custom whitespace regex

### ISSUE THREAD

**Issue by yunyu** [moroshko/autosuggest-trie#4]
I have a use case where I need to regard hyphens as whitespace, and at the moment, there doesn't seem to be a way to change the whitespace regex without modifying the library. This is what I currently use:

```javascript
const universities = JSON.parse(fs.readFileSync('universities.json'))
  .map(uni => {
    return { name: uni.name, nameIndex: replaceAll('-', ' ', uni.name), addr: uni.city + ', ' + uni.state };
  });
...
results = trie.getMatches(query, { limit: 5 }).map(result => ({ name: result.name, addr: result.addr }));
```
It would be nice to have a less hacky approach.

**Comment by moroshko** [comment]
I see. Makes sense. 
We could add `options.whitespaceRegex` to `createTrie`.
Would you like to submit a PR?

**Comment by moroshko** [comment]
[v2.1.0](https://github.com/moroshko/autosuggest-trie/releases/tag/v2.1.0) ships with `options.splitRegex` for `createTrie`. 
Could you please test it and let me know if it works for you as expected?

**Comment by yunyu** [comment]
Works with /\s+|-/, thanks for merging
